name: camera_web
description: A Flutter plugin for getting information about and controlling the camera on Web.
publish_to: "none"
#repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_web
#issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.3.2+3

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: camera
    platforms:
      web:
        pluginClass: CameraPlugin
        fileName: camera_web.dart

dependencies:
  # camera_platform_interface: ^2.3.1
  camera_platform_interface: 
    git:
      url: https://github.com/tmhoang1904/camera_extensions.git
      ref: master
      path: camera_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - camera
